image:
  file: .gitpod.dockerfile
ports:
  - port: 8888
    visibility: public
    onOpen: open-browser
tasks:
  - command: conda activate base
  - command: echo -e "\nalias jupyternb=\"jupyter notebook --NotebookApp.allow_origin=\'$(gp url 8888)\' --NotebookApp.token='' --NotebookApp.password=''\" >> ~/.bashrc
