image:
  file: Dockerfile
ports:
  - port: 8888
    visibility: public
    onOpen: notify
workspaceLocation: xbasic
checkoutLocation:  xbasic
tasks:
  - init: |
      export PATH="/home/gitpod/miniconda3/bin/:$PATH"
      conda activate base
