# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 Avinal Kumar <avinal.xlvii@gmail.com>

name: xeus-basic
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - xeus
  - nlohmann_json
  - cppzmq
  - xtl

