#! /bin/sh

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 Avinal Kumar <avinal.xlvii@gmail.com>

# Create a directory for build
mkdir build && cd build || exit

# Configure CMake
cmake -D CMAKE_INSTALL_PREFIX="/srv/conda/envs/notebook" ..

# Install the Kernel
make install