name: Documentation Improvement
description: Your suggestions for improving the xeus-basic Documentation.
labels:
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        * Before you file an issue read the Contributing guide.
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/avinal/xeus-basic/issues).

  - type: textarea
    attributes:
      label: Description
      description: A brief description of the Documentation Improvement or New Section request.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Link to Documentation Page
      description: Where the confusion/inconsistency/incomplete documentation is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Versions
      description: Last commit id on master
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: assignees
      description: Do you want to work on this issue?
      options:
        - label: Yes, I'd like to work
          required: false